[package]
name = "browser-file-reader-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.70"
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
web-sys = { version = "0.3.70", features = ["File", "console"]}

[lib]
crate-type = ["cdylib", "rlib"]
